#Exercise 1: What is the function of the secondary memory in a computer?
 # ans: Store information for the long term, even beyond a power cycle

 #Exercise 2: What is a program?
 # ans: Program is a sequence of Python statements that have been crafted to do something.

# Exercise 3: What is the difference between a compiler and an interpreter?
# ans: An interpreter reads the source code of the program as written by the programmer,parses the source code, and interprets the instructions on the fly 
#  while A compiler needs to be handed the entire program in a file,
# and then it runs a process to translate the high-level source code into machine language and then the compiler puts the resulting machine language into a file for later execution.

# Exercise 4: Which of the following contains “machine code”?
 # ans:  The Python interpreter

# Exercise 5: What is wrong with the following code:
# >>> primt 'Hello world!'
# File "<stdin>", line 1
 # primt 'Hello world!'

# Exercise 6: Where in the computer is a variable such as “x” stored after the following Python line finishes?
# x = 123
 # ans: Main Memory

#Exercise 7: What will the following program print out:
# x = 43
# x = x- 1
# print(x)
 # ans: 42

# Exercise 8: Explain each of the following using an example of a human capability:
# (1) Central processing unit, (2) Main Memory, (3) Secondary Memory, (4) Input
# Device, and (5) Output Device. For example, “What is the human equivalent to a Central Processing Unit”?
 # ans:  1. Central processing Unit - Brain - processes information  
  # 2. Main Memory - Short term/working memory - holds information temporarily 
  # 3. Secondary Memory - Long term memory - stores information permanently 
  # 4. Input Device - Senses - recieves information 
  # 5. Output Device - Means of Communication - communicates the result 